repos:
  - repo: local
    hooks:
      - id: add-license-header
        name: Add License Header
        entry: python3 scripts/add_license_header.py
        language: system
        types: [file]
        files: ^cex/src/.*\.(jsx|tsx|sh)$
