// Copyright 2025 chenjjiaa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export const countriesCN = [
    { code: 'CN', name: '中国' },
    { code: 'US', name: '美国' },
    { code: 'JP', name: '日本' },
    { code: 'KR', name: '韩国' },
    { code: 'SG', name: '新加坡' },
    { code: 'HK', name: '香港' },
    { code: 'TW', name: '台湾' },
    { code: 'AU', name: '澳大利亚' },
    { code: 'CA', name: '加拿大' },
    { code: 'GB', name: '英国' },
    { code: 'DE', name: '德国' },
    { code: 'FR', name: '法国' },
    { code: 'IT', name: '意大利' },
    { code: 'ES', name: '西班牙' },
    { code: 'NL', name: '荷兰' },
    { code: 'CH', name: '瑞士' },
    { code: 'SE', name: '瑞典' },
    { code: 'NO', name: '挪威' },
    { code: 'DK', name: '丹麦' },
    { code: 'FI', name: '芬兰' },
    { code: 'RU', name: '俄罗斯' },
    { code: 'BR', name: '巴西' },
    { code: 'MX', name: '墨西哥' },
    { code: 'AR', name: '阿根廷' },
    { code: 'IN', name: '印度' },
    { code: 'TH', name: '泰国' },
    { code: 'VN', name: '越南' },
    { code: 'MY', name: '马来西亚' },
    { code: 'ID', name: '印度尼西亚' },
    { code: 'PH', name: '菲律宾' },
    { code: 'AE', name: '阿联酋' },
    { code: 'SA', name: '沙特阿拉伯' },
    { code: 'TR', name: '土耳其' },
    { code: 'ZA', name: '南非' },
    { code: 'EG', name: '埃及' },
    { code: 'NG', name: '尼日利亚' },
    { code: 'KE', name: '肯尼亚' },
    { code: 'GH', name: '加纳' },
    { code: 'UG', name: '乌干达' },
    { code: 'TZ', name: '坦桑尼亚' },
    { code: 'ET', name: '埃塞俄比亚' },
    { code: 'DZ', name: '阿尔及利亚' },
    { code: 'MA', name: '摩洛哥' },
    { code: 'TN', name: '突尼斯' },
    { code: 'LY', name: '利比亚' },
    { code: 'SD', name: '苏丹' },
    { code: 'SS', name: '南苏丹' },
    { code: 'CF', name: '中非共和国' },
    { code: 'TD', name: '乍得' },
    { code: 'NE', name: '尼日尔' },
    { code: 'ML', name: '马里' },
    { code: 'BF', name: '布基纳法索' },
    { code: 'CI', name: '科特迪瓦' },
    { code: 'SN', name: '塞内加尔' },
    { code: 'GN', name: '几内亚' },
    { code: 'SL', name: '塞拉利昂' },
    { code: 'LR', name: '利比里亚' },
    { code: 'TG', name: '多哥' },
    { code: 'BJ', name: '贝宁' },
    { code: 'GW', name: '几内亚比绍' },
    { code: 'CV', name: '佛得角' },
    { code: 'GM', name: '冈比亚' },
    { code: 'MR', name: '毛里塔尼亚' },
    { code: 'MZ', name: '莫桑比克' },
    { code: 'ZW', name: '津巴布韦' },
    { code: 'BW', name: '博茨瓦纳' },
    { code: 'NA', name: '纳米比亚' },
    { code: 'LS', name: '莱索托' },
    { code: 'SZ', name: '斯威士兰' },
    { code: 'MG', name: '马达加斯加' },
    { code: 'MU', name: '毛里求斯' },
    { code: 'SC', name: '塞舌尔' },
    { code: 'KM', name: '科摩罗' },
    { code: 'DJ', name: '吉布提' },
    { code: 'SO', name: '索马里' },
    { code: 'ER', name: '厄立特里亚' },
    { code: 'YE', name: '也门' },
    { code: 'OM', name: '阿曼' },
    { code: 'QA', name: '卡塔尔' },
    { code: 'BH', name: '巴林' },
    { code: 'KW', name: '科威特' },
    { code: 'JO', name: '约旦' },
    { code: 'LB', name: '黎巴嫩' },
    { code: 'SY', name: '叙利亚' },
    { code: 'IQ', name: '伊拉克' },
    { code: 'IR', name: '伊朗' },
    { code: 'AF', name: '阿富汗' },
    { code: 'PK', name: '巴基斯坦' },
    { code: 'BD', name: '孟加拉国' },
    { code: 'LK', name: '斯里兰卡' },
    { code: 'NP', name: '尼泊尔' },
    { code: 'BT', name: '不丹' },
    { code: 'MM', name: '缅甸' },
    { code: 'LA', name: '老挝' },
    { code: 'KH', name: '柬埔寨' },
    { code: 'MN', name: '蒙古' },
    { code: 'KZ', name: '哈萨克斯坦' },
    { code: 'UZ', name: '乌兹别克斯坦' },
    { code: 'KG', name: '吉尔吉斯斯坦' },
    { code: 'TJ', name: '塔吉克斯坦' },
    { code: 'TM', name: '土库曼斯坦' },
    { code: 'AZ', name: '阿塞拜疆' },
    { code: 'GE', name: '格鲁吉亚' },
    { code: 'AM', name: '亚美尼亚' },
    { code: 'BY', name: '白俄罗斯' },
    { code: 'UA', name: '乌克兰' },
    { code: 'MD', name: '摩尔多瓦' },
    { code: 'RO', name: '罗马尼亚' },
    { code: 'BG', name: '保加利亚' },
    { code: 'RS', name: '塞尔维亚' },
    { code: 'HR', name: '克罗地亚' },
    { code: 'SI', name: '斯洛文尼亚' },
    { code: 'BA', name: '波斯尼亚和黑塞哥维那' },
    { code: 'ME', name: '黑山' },
    { code: 'MK', name: '北马其顿' },
    { code: 'AL', name: '阿尔巴尼亚' },
    { code: 'GR', name: '希腊' },
    { code: 'CY', name: '塞浦路斯' },
    { code: 'MT', name: '马耳他' },
    { code: 'PT', name: '葡萄牙' },
    { code: 'IE', name: '爱尔兰' },
    { code: 'IS', name: '冰岛' },
    { code: 'PL', name: '波兰' },
    { code: 'CZ', name: '捷克' },
    { code: 'SK', name: '斯洛伐克' },
    { code: 'HU', name: '匈牙利' },
    { code: 'AT', name: '奥地利' },
    { code: 'LU', name: '卢森堡' },
    { code: 'BE', name: '比利时' },
    { code: 'LI', name: '列支敦士登' },
    { code: 'MC', name: '摩纳哥' },
    { code: 'AD', name: '安道尔' },
    { code: 'SM', name: '圣马力诺' },
    { code: 'VA', name: '梵蒂冈' },
    { code: 'NZ', name: '新西兰' },
    { code: 'FJ', name: '斐济' },
    { code: 'PG', name: '巴布亚新几内亚' },
    { code: 'SB', name: '所罗门群岛' },
    { code: 'VU', name: '瓦努阿图' },
    { code: 'NC', name: '新喀里多尼亚' },
    { code: 'PF', name: '法属波利尼西亚' },
    { code: 'TO', name: '汤加' },
    { code: 'WS', name: '萨摩亚' },
    { code: 'KI', name: '基里巴斯' },
    { code: 'TV', name: '图瓦卢' },
    { code: 'NR', name: '瑙鲁' },
    { code: 'PW', name: '帕劳' },
    { code: 'MH', name: '马绍尔群岛' },
    { code: 'FM', name: '密克罗尼西亚' },
    { code: 'GU', name: '关岛' },
    { code: 'MP', name: '北马里亚纳群岛' },
    { code: 'AS', name: '美属萨摩亚' },
    { code: 'CK', name: '库克群岛' },
    { code: 'NU', name: '纽埃' },
    { code: 'TK', name: '托克劳' },
    { code: 'WF', name: '瓦利斯和富图纳' }
];

export const countriesEN = [
    { code: 'CN', name: 'China' },
    { code: 'US', name: 'United States' },
    { code: 'JP', name: 'Japan' },
    { code: 'KR', name: 'South Korea' },
    { code: 'SG', name: 'Singapore' },
    { code: 'HK', name: 'Hong Kong' },
    { code: 'TW', name: 'Taiwan' },
    { code: 'AU', name: 'Australia' },
    { code: 'CA', name: 'Canada' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'DE', name: 'Germany' },
    { code: 'FR', name: 'France' },
    { code: 'IT', name: 'Italy' },
    { code: 'ES', name: 'Spain' },
    { code: 'NL', name: 'Netherlands' },
    { code: 'CH', name: 'Switzerland' },
    { code: 'SE', name: 'Sweden' },
    { code: 'NO', name: 'Norway' },
    { code: 'DK', name: 'Denmark' },
    { code: 'FI', name: 'Finland' },
    { code: 'RU', name: 'Russia' },
    { code: 'BR', name: 'Brazil' },
    { code: 'MX', name: 'Mexico' },
    { code: 'AR', name: 'Argentina' },
    { code: 'IN', name: 'India' },
    { code: 'TH', name: 'Thailand' },
    { code: 'VN', name: 'Vietnam' },
    { code: 'MY', name: 'Malaysia' },
    { code: 'ID', name: 'Indonesia' },
    { code: 'PH', name: 'Philippines' },
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'SA', name: 'Saudi Arabia' },
    { code: 'TR', name: 'Turkey' },
    { code: 'ZA', name: 'South Africa' },
    { code: 'EG', name: 'Egypt' },
    { code: 'NG', name: 'Nigeria' },
    { code: 'KE', name: 'Kenya' },
    { code: 'GH', name: 'Ghana' },
    { code: 'UG', name: 'Uganda' },
    { code: 'TZ', name: 'Tanzania' },
    { code: 'ET', name: 'Ethiopia' },
    { code: 'DZ', name: 'Algeria' },
    { code: 'MA', name: 'Morocco' },
    { code: 'TN', name: 'Tunisia' },
    { code: 'LY', name: 'Libya' },
    { code: 'SD', name: 'Sudan' },
    { code: 'SS', name: 'South Sudan' },
    { code: 'CF', name: 'Central African Republic' },
    { code: 'TD', name: 'Chad' },
    { code: 'NE', name: 'Niger' },
    { code: 'ML', name: 'Mali' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'CI', name: 'Ivory Coast' },
    { code: 'SN', name: 'Senegal' },
    { code: 'GN', name: 'Guinea' },
    { code: 'SL', name: 'Sierra Leone' },
    { code: 'LR', name: 'Liberia' },
    { code: 'TG', name: 'Togo' },
    { code: 'BJ', name: 'Benin' },
    { code: 'GW', name: 'Guinea-Bissau' },
    { code: 'CV', name: 'Cape Verde' },
    { code: 'GM', name: 'Gambia' },
    { code: 'MR', name: 'Mauritania' },
    { code: 'BW', name: 'Botswana' },
    { code: 'ZW', name: 'Zimbabwe' },
    { code: 'ZM', name: 'Zambia' },
    { code: 'MW', name: 'Malawi' },
    { code: 'MZ', name: 'Mozambique' },
    { code: 'SZ', name: 'Eswatini' },
    { code: 'LS', name: 'Lesotho' },
    { code: 'NA', name: 'Namibia' },
    { code: 'MG', name: 'Madagascar' },
    { code: 'MU', name: 'Mauritius' },
    { code: 'SC', name: 'Seychelles' },
    { code: 'KM', name: 'Comoros' },
    { code: 'DJ', name: 'Djibouti' },
    { code: 'SO', name: 'Somalia' },
    { code: 'ER', name: 'Eritrea' },
    { code: 'CM', name: 'Cameroon' },
    { code: 'GQ', name: 'Equatorial Guinea' },
    { code: 'GA', name: 'Gabon' },
    { code: 'CG', name: 'Republic of the Congo' },
    { code: 'CD', name: 'Democratic Republic of the Congo' },
    { code: 'AO', name: 'Angola' },
    { code: 'ST', name: 'São Tomé and Príncipe' },
    { code: 'RW', name: 'Rwanda' },
    { code: 'BI', name: 'Burundi' },
    { code: 'PK', name: 'Pakistan' },
    { code: 'BD', name: 'Bangladesh' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'NP', name: 'Nepal' },
    { code: 'BT', name: 'Bhutan' },
    { code: 'MV', name: 'Maldives' },
    { code: 'MM', name: 'Myanmar' },
    { code: 'LA', name: 'Laos' },
    { code: 'KH', name: 'Cambodia' },
    { code: 'BN', name: 'Brunei' },
    { code: 'TL', name: 'East Timor' },
    { code: 'MN', name: 'Mongolia' },
    { code: 'KZ', name: 'Kazakhstan' },
    { code: 'UZ', name: 'Uzbekistan' },
    { code: 'KG', name: 'Kyrgyzstan' },
    { code: 'TJ', name: 'Tajikistan' },
    { code: 'TM', name: 'Turkmenistan' },
    { code: 'AF', name: 'Afghanistan' },
    { code: 'IR', name: 'Iran' },
    { code: 'IQ', name: 'Iraq' },
    { code: 'SY', name: 'Syria' },
    { code: 'LB', name: 'Lebanon' },
    { code: 'JO', name: 'Jordan' },
    { code: 'IL', name: 'Israel' },
    { code: 'PS', name: 'Palestine' },
    { code: 'KW', name: 'Kuwait' },
    { code: 'QA', name: 'Qatar' },
    { code: 'BH', name: 'Bahrain' },
    { code: 'OM', name: 'Oman' },
    { code: 'YE', name: 'Yemen' },
    { code: 'BG', name: 'Bulgaria' },
    { code: 'RS', name: 'Serbia' },
    { code: 'HR', name: 'Croatia' },
    { code: 'SI', name: 'Slovenia' },
    { code: 'BA', name: 'Bosnia and Herzegovina' },
    { code: 'ME', name: 'Montenegro' },
    { code: 'MK', name: 'North Macedonia' },
    { code: 'AL', name: 'Albania' },
    { code: 'GR', name: 'Greece' },
    { code: 'CY', name: 'Cyprus' },
    { code: 'MT', name: 'Malta' },
    { code: 'PT', name: 'Portugal' },
    { code: 'IE', name: 'Ireland' },
    { code: 'IS', name: 'Iceland' },
    { code: 'PL', name: 'Poland' },
    { code: 'CZ', name: 'Czech Republic' },
    { code: 'SK', name: 'Slovakia' },
    { code: 'HU', name: 'Hungary' },
    { code: 'AT', name: 'Austria' },
    { code: 'LU', name: 'Luxembourg' },
    { code: 'BE', name: 'Belgium' },
    { code: 'LI', name: 'Liechtenstein' },
    { code: 'MC', name: 'Monaco' },
    { code: 'AD', name: 'Andorra' },
    { code: 'SM', name: 'San Marino' },
    { code: 'VA', name: 'Vatican City' },
    { code: 'NZ', name: 'New Zealand' },
    { code: 'FJ', name: 'Fiji' },
    { code: 'PG', name: 'Papua New Guinea' },
    { code: 'SB', name: 'Solomon Islands' },
    { code: 'VU', name: 'Vanuatu' },
    { code: 'NC', name: 'New Caledonia' },
    { code: 'PF', name: 'French Polynesia' },
    { code: 'TO', name: 'Tonga' },
    { code: 'WS', name: 'Samoa' },
    { code: 'KI', name: 'Kiribati' },
    { code: 'TV', name: 'Tuvalu' },
    { code: 'NR', name: 'Nauru' },
    { code: 'PW', name: 'Palau' },
    { code: 'MH', name: 'Marshall Islands' },
    { code: 'FM', name: 'Micronesia' },
    { code: 'GU', name: 'Guam' },
    { code: 'MP', name: 'Northern Mariana Islands' },
    { code: 'AS', name: 'American Samoa' },
    { code: 'CK', name: 'Cook Islands' },
    { code: 'NU', name: 'Niue' },
    { code: 'TK', name: 'Tokelau' },
    { code: 'WF', name: 'Wallis and Futuna' },
];