// Copyright 2025 chenjjiaa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

export const phoneCountriesCN = [
  { code: 'CN', name: '中国', phone: '+86' },
  { code: 'HK', name: '香港', phone: '+852' },
  { code: 'TW', name: '台湾', phone: '+886' },
  { code: 'MO', name: '澳门', phone: '+853' },
  { code: 'US', name: '美国', phone: '+1' },
  { code: 'CA', name: '加拿大', phone: '+1' },
  { code: 'JP', name: '日本', phone: '+81' },
  { code: 'KR', name: '韩国', phone: '+82' },
  { code: 'SG', name: '新加坡', phone: '+65' },
  { code: 'AU', name: '澳大利亚', phone: '+61' },
  { code: 'GB', name: '英国', phone: '+44' },
  { code: 'DE', name: '德国', phone: '+49' },
  { code: 'FR', name: '法国', phone: '+33' },
  { code: 'IT', name: '意大利', phone: '+39' },
  { code: 'ES', name: '西班牙', phone: '+34' },
  { code: 'NL', name: '荷兰', phone: '+31' },
  { code: 'CH', name: '瑞士', phone: '+41' },
  { code: 'SE', name: '瑞典', phone: '+46' },
  { code: 'NO', name: '挪威', phone: '+47' },
  { code: 'DK', name: '丹麦', phone: '+45' },
  { code: 'FI', name: '芬兰', phone: '+358' },
  { code: 'RU', name: '俄罗斯', phone: '+7' },
  { code: 'BR', name: '巴西', phone: '+55' },
  { code: 'MX', name: '墨西哥', phone: '+52' },
  { code: 'AR', name: '阿根廷', phone: '+54' },
  { code: 'IN', name: '印度', phone: '+91' },
  { code: 'TH', name: '泰国', phone: '+66' },
  { code: 'VN', name: '越南', phone: '+84' },
  { code: 'MY', name: '马来西亚', phone: '+60' },
  { code: 'ID', name: '印度尼西亚', phone: '+62' },
  { code: 'PH', name: '菲律宾', phone: '+63' },
  { code: 'AE', name: '阿联酋', phone: '+971' },
  { code: 'SA', name: '沙特阿拉伯', phone: '+966' },
  { code: 'TR', name: '土耳其', phone: '+90' },
  { code: 'ZA', name: '南非', phone: '+27' },
  { code: 'EG', name: '埃及', phone: '+20' },
  { code: 'NG', name: '尼日利亚', phone: '+234' },
  { code: 'KE', name: '肯尼亚', phone: '+254' },
  { code: 'GH', name: '加纳', phone: '+233' },
  { code: 'IL', name: '以色列', phone: '+972' },
  { code: 'QA', name: '卡塔尔', phone: '+974' },
  { code: 'BH', name: '巴林', phone: '+973' },
  { code: 'KW', name: '科威特', phone: '+965' },
  { code: 'OM', name: '阿曼', phone: '+968' },
  { code: 'JO', name: '约旦', phone: '+962' },
  { code: 'LB', name: '黎巴嫩', phone: '+961' },
  { code: 'PK', name: '巴基斯坦', phone: '+92' },
  { code: 'BD', name: '孟加拉国', phone: '+880' },
  { code: 'LK', name: '斯里兰卡', phone: '+94' },
  { code: 'NP', name: '尼泊尔', phone: '+977' },
  { code: 'MM', name: '缅甸', phone: '+95' },
  { code: 'LA', name: '老挝', phone: '+856' },
  { code: 'KH', name: '柬埔寨', phone: '+855' },
  { code: 'MN', name: '蒙古', phone: '+976' },
  { code: 'KZ', name: '哈萨克斯坦', phone: '+7' },
  { code: 'UZ', name: '乌兹别克斯坦', phone: '+998' },
  { code: 'AT', name: '奥地利', phone: '+43' },
  { code: 'BE', name: '比利时', phone: '+32' },
  { code: 'PT', name: '葡萄牙', phone: '+351' },
  { code: 'GR', name: '希腊', phone: '+30' },
  { code: 'IE', name: '爱尔兰', phone: '+353' },
  { code: 'PL', name: '波兰', phone: '+48' },
  { code: 'CZ', name: '捷克', phone: '+420' },
  { code: 'HU', name: '匈牙利', phone: '+36' },
  { code: 'NZ', name: '新西兰', phone: '+64' },
  { code: 'CL', name: '智利', phone: '+56' },
  { code: 'PE', name: '秘鲁', phone: '+51' },
  { code: 'CO', name: '哥伦比亚', phone: '+57' },
  { code: 'VE', name: '委内瑞拉', phone: '+58' },
  { code: 'UY', name: '乌拉圭', phone: '+598' },
  { code: 'PY', name: '巴拉圭', phone: '+595' },
  { code: 'BO', name: '玻利维亚', phone: '+591' },
  { code: 'EC', name: '厄瓜多尔', phone: '+593' },
  { code: 'LU', name: '卢森堡', phone: '+352' },
  { code: 'IS', name: '冰岛', phone: '+354' },
  { code: 'MT', name: '马耳他', phone: '+356' },
  { code: 'CY', name: '塞浦路斯', phone: '+357' },
];

export const phoneCountriesEN = [
  { code: 'CN', name: 'China', phone: '+86' },
  { code: 'HK', name: 'Hong Kong', phone: '+852' },
  { code: 'TW', name: 'Taiwan', phone: '+886' },
  { code: 'MO', name: 'Macao', phone: '+853' },
  { code: 'US', name: 'United States', phone: '+1' },
  { code: 'CA', name: 'Canada', phone: '+1' },
  { code: 'JP', name: 'Japan', phone: '+81' },
  { code: 'KR', name: 'South Korea', phone: '+82' },
  { code: 'SG', name: 'Singapore', phone: '+65' },
  { code: 'AU', name: 'Australia', phone: '+61' },
  { code: 'GB', name: 'United Kingdom', phone: '+44' },
  { code: 'DE', name: 'Germany', phone: '+49' },
  { code: 'FR', name: 'France', phone: '+33' },
  { code: 'IT', name: 'Italy', phone: '+39' },
  { code: 'ES', name: 'Spain', phone: '+34' },
  { code: 'NL', name: 'Netherlands', phone: '+31' },
  { code: 'CH', name: 'Switzerland', phone: '+41' },
  { code: 'SE', name: 'Sweden', phone: '+46' },
  { code: 'NO', name: 'Norway', phone: '+47' },
  { code: 'DK', name: 'Denmark', phone: '+45' },
  { code: 'FI', name: 'Finland', phone: '+358' },
  { code: 'RU', name: 'Russia', phone: '+7' },
  { code: 'BR', name: 'Brazil', phone: '+55' },
  { code: 'MX', name: 'Mexico', phone: '+52' },
  { code: 'AR', name: 'Argentina', phone: '+54' },
  { code: 'IN', name: 'India', phone: '+91' },
  { code: 'TH', name: 'Thailand', phone: '+66' },
  { code: 'VN', name: 'Vietnam', phone: '+84' },
  { code: 'MY', name: 'Malaysia', phone: '+60' },
  { code: 'ID', name: 'Indonesia', phone: '+62' },
  { code: 'PH', name: 'Philippines', phone: '+63' },
  { code: 'AE', name: 'United Arab Emirates', phone: '+971' },
  { code: 'SA', name: 'Saudi Arabia', phone: '+966' },
  { code: 'TR', name: 'Turkey', phone: '+90' },
  { code: 'ZA', name: 'South Africa', phone: '+27' },
  { code: 'EG', name: 'Egypt', phone: '+20' },
  { code: 'NG', name: 'Nigeria', phone: '+234' },
  { code: 'KE', name: 'Kenya', phone: '+254' },
  { code: 'GH', name: 'Ghana', phone: '+233' },
  { code: 'IL', name: 'Israel', phone: '+972' },
  { code: 'QA', name: 'Qatar', phone: '+974' },
  { code: 'BH', name: 'Bahrain', phone: '+973' },
  { code: 'KW', name: 'Kuwait', phone: '+965' },
  { code: 'OM', name: 'Oman', phone: '+968' },
  { code: 'JO', name: 'Jordan', phone: '+962' },
  { code: 'LB', name: 'Lebanon', phone: '+961' },
  { code: 'PK', name: 'Pakistan', phone: '+92' },
  { code: 'BD', name: 'Bangladesh', phone: '+880' },
  { code: 'LK', name: 'Sri Lanka', phone: '+94' },
  { code: 'NP', name: 'Nepal', phone: '+977' },
  { code: 'MM', name: 'Myanmar', phone: '+95' },
  { code: 'LA', name: 'Laos', phone: '+856' },
  { code: 'KH', name: 'Cambodia', phone: '+855' },
  { code: 'MN', name: 'Mongolia', phone: '+976' },
  { code: 'KZ', name: 'Kazakhstan', phone: '+7' },
  { code: 'UZ', name: 'Uzbekistan', phone: '+998' },
  { code: 'AT', name: 'Austria', phone: '+43' },
  { code: 'BE', name: 'Belgium', phone: '+32' },
  { code: 'PT', name: 'Portugal', phone: '+351' },
  { code: 'GR', name: 'Greece', phone: '+30' },
  { code: 'IE', name: 'Ireland', phone: '+353' },
  { code: 'PL', name: 'Poland', phone: '+48' },
  { code: 'CZ', name: 'Czech Republic', phone: '+420' },
  { code: 'HU', name: 'Hungary', phone: '+36' },
  { code: 'NZ', name: 'New Zealand', phone: '+64' },
  { code: 'CL', name: 'Chile', phone: '+56' },
  { code: 'PE', name: 'Peru', phone: '+51' },
  { code: 'CO', name: 'Colombia', phone: '+57' },
  { code: 'VE', name: 'Venezuela', phone: '+58' },
  { code: 'UY', name: 'Uruguay', phone: '+598' },
  { code: 'PY', name: 'Paraguay', phone: '+595' },
  { code: 'BO', name: 'Bolivia', phone: '+591' },
  { code: 'EC', name: 'Ecuador', phone: '+593' },
  { code: 'LU', name: 'Luxembourg', phone: '+352' },
  { code: 'IS', name: 'Iceland', phone: '+354' },
  { code: 'MT', name: 'Malta', phone: '+356' },
  { code: 'CY', name: 'Cyprus', phone: '+357' },
]; 